# Generated by Django 2.2.4 on 2019-08-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='component',
            name='components',
        ),
        migrations.AlterField(
            model_name='basetemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
