# Generated by Django 2.2.4 on 2019-08-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0002_auto_20190817_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='components',
            field=models.ManyToManyField(through='hbemail.ModuleComponent', to='hbemail.Component'),
        ),
    ]
