# Generated by Django 2.2.4 on 2019-08-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0003_module_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hbemail.Content'),
        ),
    ]
