# Generated by Django 2.2.4 on 2019-08-17 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0005_auto_20190817_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hbemail.Category'),
        ),
    ]
