# Generated by Django 2.2.4 on 2019-08-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0006_template_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'TemplateCategories',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ComponentCategory',
        ),
        migrations.AlterModelOptions(
            name='componentcategory',
            options={'verbose_name_plural': 'ComponentCategories'},
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hbemail.TemplateCategory'),
        ),
    ]
