# Generated by Django 2.2.4 on 2019-08-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0007_auto_20190817_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='data',
            new_name='html',
        ),
        migrations.AddField(
            model_name='template',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
