# Generated by Django 2.2.4 on 2019-08-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0009_region_templateregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateregion',
            name='html',
            field=models.TextField(blank=True),
        ),
    ]
