# Generated by Django 2.2.4 on 2019-08-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0011_componentschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='schema',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
