# Generated by Django 2.2.4 on 2019-08-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0012_component_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
