# Generated by Django 2.2.4 on 2019-08-20 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0013_auto_20190819_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hbemail.Component'),
        ),
    ]
