# Generated by Django 2.2.4 on 2019-08-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0015_auto_20190820_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
