# Generated by Django 2.2.4 on 2019-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0016_auto_20190820_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='data_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('yaml', 'YAML'), ('html', 'HTML')], default='markdown', max_length=64),
        ),
    ]
