# Generated by Django 2.2.4 on 2019-08-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0017_content_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='regions',
            field=models.ManyToManyField(through='hbemail.TemplateRegion', to='hbemail.Region'),
        ),
    ]
