# Generated by Django 2.2.4 on 2019-08-21 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0019_remove_template_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateregion',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hbemail.Content'),
        ),
    ]
