# Generated by Django 2.2.4 on 2019-08-22 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0020_templateregion_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='data_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('yaml', 'YAML'), ('mjml', 'MJML'), ('htmlmixed', 'HTML')], default='markdown', max_length=64),
        ),
    ]
