# Generated by Django 2.2.4 on 2019-08-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0021_auto_20190822_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('html', models.TextField(blank=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hbemail.Content')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hbemail.Template')),
            ],
        ),
        migrations.RemoveField(
            model_name='templateregion',
            name='content',
        ),
        migrations.RemoveField(
            model_name='templateregion',
            name='region',
        ),
        migrations.RemoveField(
            model_name='templateregion',
            name='template',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='TemplateRegion',
        ),
    ]
