# Generated by Django 2.2.4 on 2019-08-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0022_auto_20190822_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatecontent',
            old_name='html',
            new_name='data',
        ),
    ]
