# Generated by Django 2.2.4 on 2019-08-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0024_templatecontent_var_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='preheaderText',
            field=models.CharField(default='preheader', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='subject',
            field=models.CharField(default='subject', max_length=256),
            preserve_default=False,
        ),
    ]
