# Generated by Django 2.2.4 on 2019-09-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0027_auto_20190904_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='parent',
        ),
        migrations.AddField(
            model_name='component',
            name='markup_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('mjml', 'MJML'), ('htmlmixed', 'HTML'), ('iterable', 'Iterable')], default='markdown', max_length=64),
        ),
        migrations.AlterField(
            model_name='content',
            name='data_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('yaml', 'YAML'), ('mjml', 'MJML'), ('htmlmixed', 'HTML'), ('iterable', 'Iterable'), ('inherit', 'Inherit')], default='inherit', max_length=64),
        ),
    ]
