# Generated by Django 2.2.4 on 2019-09-04 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hbemail', '0028_auto_20190904_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
