# Generated by Django 2.2.4 on 2019-09-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_id', models.CharField(max_length=64)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=256)),
                ('short_title', models.CharField(max_length=256)),
                ('type', models.CharField(default='audio', max_length=32)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('meditation', 'Meditation'), ('sleep', 'Sleep'), ('sequential', 'Sequential'), ('masterclass', 'Masterclass')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=64)),
                ('author', models.CharField(blank=True, max_length=128, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calm.Language')),
                ('meditation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calm.MeditationType')),
            ],
        ),
        migrations.CreateModel(
            name='GuideCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('markdown', 'markdown'), ('htmlmixed', 'html')], default='markdown', max_length=32, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('_rendered_data', models.TextField(blank=True, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calm.Guide')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calm.Language'),
        ),
        migrations.AddField(
            model_name='guide',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calm.Program'),
        ),
    ]
