# Generated by Django 2.2.4 on 2019-09-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English')], default='en', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English')], default='en', max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
