# Generated by Django 2.2.4 on 2019-09-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0002_auto_20190909_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='meditation_type',
            field=models.CharField(blank=True, choices=[('meditation', 'Meditation'), ('sleep', 'Sleep'), ('sequential', 'Sequential'), ('masterclass', 'Masterclass')], max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='MeditationType',
        ),
    ]
