# Generated by Django 2.2.4 on 2019-09-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0003_auto_20190909_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='background_image',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='narrator',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='narrator_image',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='titled_background_image',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
