# Generated by Django 2.2.4 on 2019-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0004_auto_20190909_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecampaign',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
