# Generated by Django 2.2.4 on 2019-09-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0005_guidecampaign_test'),
    ]

    operations = [
    ]
