# Generated by Django 2.2.4 on 2019-09-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0007_guideextrainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideEmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(blank=True, choices=[('markdown', 'markdown'), ('htmlmixed', 'html')], default='markdown', max_length=32, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('test', models.TextField(blank=True, null=True)),
                ('_rendered_data', models.TextField(blank=True, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calm.Guide')),
            ],
        ),
        migrations.DeleteModel(
            name='GuideCampaign',
        ),
    ]
