# Generated by Django 2.2.4 on 2019-09-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0008_auto_20190910_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuideExtraInfo',
        ),
    ]
