# Generated by Django 2.2.4 on 2019-09-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0009_delete_guideextrainfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideemailcampaign',
            name='_rendered_data',
        ),
        migrations.AddField(
            model_name='guide',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guideemailcampaign',
            name='format',
            field=models.CharField(blank=True, choices=[('htmlmixed', 'html'), ('javascript', 'js'), ('markdown', 'markdown')], default='markdown', max_length=32, null=True),
        ),
    ]
