# Generated by Django 2.2.4 on 2019-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterablegen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterablesnippet',
            name='markup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iterablesnippet',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
