# Generated by Django 2.2.4 on 2019-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterablegen', '0002_auto_20190904_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterablecampaignsnippet',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
