# Generated by Django 2.2.4 on 2019-09-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterablegen', '0004_iterablecampaigncategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iterablecampaigncategory',
            options={'verbose_name_plural': 'IterableCampaignCategories'},
        ),
        migrations.AddField(
            model_name='iterablecampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=128),
        ),
    ]
