# Generated by Django 2.2.4 on 2019-09-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterablegen', '0005_auto_20190905_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterablecampaign',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='iterablegen.IterableCampaignCategory'),
        ),
    ]
