# Generated by Django 2.2.4 on 2019-09-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calm', '0011_auto_20190910_2145'),
        ('iterablegen', '0008_iterablecampaign_campaignid'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterablecampaignsnippet',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calm.Guide'),
        ),
    ]
